In [27]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

def dgp_ate4_int(n, var_e):
    np.random.seed()
    #treatment (randomly assigned)
    d = np.random.choice([0, 1], size=(n,1), p=[1./2, 1./2])
    #covariates (relevate to T.E.)
    x1 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
    x2 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
    #covariates (relevant to outcome)
    x3 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
    x4 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
    x5 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
    #covariates (irrelevant)
    x6 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
    #error term
    e = np.random.normal(loc = 0.0, scale = var_e, size = (n,1))

    #indicator functions
    ind1 = np.zeros((n,1))
    ind2 = np.zeros((n,1))
    ind3 = np.zeros((n,1))
    ind1[np.where(x1 >= 0)] = 1
    ind2[np.where(x2 >= 0)] = 1
    ind3[np.where((x1 >= 0) & (x2 >= 0))] = 1

    y = np.add(np.add(np.add(np.add(np.add(d*-2, np.multiply(np.add(np.add(3*ind1, ind2), ind3),d)),x3),x4),x5),e)
    X = np.concatenate((x1,x2,x3,x4,x5,x6), axis=1)
    
    x_train, x_test, y_train, y_test, treat_train, treat_test = train_test_split(X, y, d, test_size=0.5)
    
    return x_train, x_test, y_train, y_test, treat_train, treat_test


x_train, x_test, y_train, y_test, treat_train, treat_test = dgp_ate4_int(1000, 0.01)

x1 = x_test[:,0].reshape(-1,1)
x2 = x_test[:,1].reshape(-1,1)
d = treat_test[:,0].reshape(-1,1)
y = y_test[:,0].reshape(-1,1)
print(np.mean(y[np.where((x1 >= 0) & (x2 >= 0) & (d == 1))]) - np.mean(y[np.where((x1 >= 0) & (x2 >= 0) & (d == 0))]))
print(np.mean(y[np.where((x1 >= 0) & (x2 < 0) & (d == 1))]) - np.mean(y[np.where((x1 >= 0) & (x2 < 0) & (d == 0))]))
print(np.mean(y[np.where((x1 < 0) & (x2 >= 0) & (d == 1))]) - np.mean(y[np.where((x1 < 0) & (x2 >= 0) & (d == 0))]))
print(np.mean(y[np.where((x1 < 0) & (x2 < 0) & (d == 1))]) - np.mean(y[np.where((x1 < 0) & (x2 < 0) & (d == 0))]))


2.504040966396434
1.4063496774923718
-0.5112420393166374
-2.0111087870890376


In [14]:
def dgp4(n, var_e):
    np.random.seed()
    p=[1./2, 1./2]
    d = np.random.choice([0, 1], size=(n,1), p=p)
    x1 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
    x2 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
    x3 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
    x4 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))    
    e = np.random.normal(loc = 0.0, scale = var_e, size = (n,1))

    ind = np.zeros((n,1))
    ind[np.where(x1 >= 0)] = 1
    y = np.add(np.add(np.add(np.add(np.add(d*-1.5, np.multiply(3*d, ind)),x2),x3),x4),e)

    X = np.concatenate((x1,x2,x3,x4), axis=1)


    #X = np.concatenate((X,d), axis = 1)
    x_train, x_test, y_train, y_test, treat_train, treat_test = train_test_split(X, y, d, test_size=0.5)

    return x_train, x_test, y_train, y_test, treat_train, treat_test

In [37]:
x_train, x_test, y_train, y_test, treat_train, treat_test = dgp_ate4_int(100000, 0.01)

x1 = x_test[:,0].reshape(-1,1)
x2 = x_test[:,1].reshape(-1,1)
d = treat_test[:,0].reshape(-1,1)
y = y_test[:,0].reshape(-1,1)


print(np.mean(y[np.where((x1 >= 0)  & (x2 >=0) & (d == 1))]) - np.mean(y[np.where((x1 >= 0) &(x2 >=0) & (d == 0))]))
print(np.mean(y[np.where((x1 >= 0)  & (x2 <0) & (d == 1))]) - np.mean(y[np.where((x1 >= 0) &(x2 <0) & (d == 0))]))
print(np.mean(y[np.where((x1 < 0)  & (x2 >=0) &(d == 1))]) - np.mean(y[np.where((x1 < 0) & (x2 >=0) &(d == 0))]))
print(np.mean(y[np.where((x1 < 0)  & (x2 <0) &(d == 1))]) - np.mean(y[np.where((x1 < 0) & (x2 <0) &(d == 0))]))

2.9900644535866405
1.0438087518111607
-0.9965434041068919
-2.0227189290104586


In [29]:
print(np.concatenate((x1,x2,d), axis =1))

[[ 2.27494285  0.78232409  0.        ]
 [ 0.37198045 -1.15665642  1.        ]
 [ 1.7637217   0.97795894  0.        ]
 ...
 [ 0.67582889 -0.36199346  1.        ]
 [-1.25187793  0.16096981  0.        ]
 [-2.03463072  0.45817305  0.        ]]


In [20]:

#print(np.mean(y[np.where((x1 >= 0) & (x2 >= 0) & (d == 1))]) - np.mean(y[np.where((x1 >= 0) & (x2 >= 0) & (d == 0))]))
#print(np.mean(y[np.where((x1 >= 0) & (x2 < 0) & (d == 1))]) - np.mean(y[np.where((x1 >= 0) & (x2 < 0) & (d == 0))]))
#print(np.mean(y[np.where((x1 < 0) & (x2 >= 0) & (d == 1))]) - np.mean(y[np.where((x1 < 0) & (x2 >= 0) & (d == 0))]))
#print(np.mean(y[np.where((x1 < 0) & (x2 < 0) & (d == 1))]) - np.mean(y[np.where((x1 < 0) & (x2 < 0) & (d == 0))]))


array([[ 1],
       [-1],
       [-2],
       [ 2],
       [ 1],
       [ 2],
       [ 1],
       [-2],
       [ 2],
       [-2]])

In [26]:
import timeit


In [25]:


%timeit()


In [23]:
tau

array([-1,  2, -1, -2, -1,  1,  1,  1, -2,  2, -2, -1,  1,  1, -1, -2,  1,
       -1, -1,  2, -2, -1,  1,  2,  1,  1,  1,  1,  1,  2,  2,  1, -2, -1,
        1, -2, -2, -1, -2, -1,  2,  2, -2, -1, -1,  2, -2, -2,  2, -2])

In [45]:
# testing timeit()
import timeit
import_module = '''
import numpy as np
from sklearn.model_selection import train_test_split
'''
testcode = ''' 
def time_test():

'''
print(np.sum(timeit.repeat(stmt=testcode, setup=import_module, repeat = 50)))

7.406819899999391


In [46]:
# testing timeit()
import timeit
import_module = '''
import numpy as np
from sklearn.model_selection import train_test_split
'''
testcode = ''' 
def time_test():
    x_train, x_test, y_train, y_test, treat_train, treat_test = dgp6(1000, 0.01)
    tau = np.where(((x_test[:,0] >= 0) & (x_test[:,1] >= 0)),2, np.where(((x_test[:,0] >= 0) & (x_test[:,1] < 0)),1, np.where(((x_test[:,0] < 0) & (x_test[:,1] >= 0)),-1,-2)))
    return tau
'''
print(np.sum(timeit.repeat(stmt=testcode, setup=import_module, repeat = 50)))

6.8403421999998955


In [30]:
x_train, x_test, y_train, y_test, treat_train, treat_test = dgp4(1000, 0.01)
x1 = x_test[:,0]
x2 = x_test[:,1]
tau1 = np.where(((x1 >= 0) & (x2 >= 0)),2, np.where(((x1 >= 0) & (x2 < 0)),1, np.where(((x1 < 0) & (x2 >= 0)),-1,-2)))

In [31]:
x1 = x_test[:,0]
x2 = x_test[:,1]

np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] >= 0) & (treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] >= 0) & (treat_test[:,0] == 0))])
np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] < 0) & (treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] < 0) & (treat_test[:,0] == 0))])
np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] >= 0) & (treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] >= 0) & (treat_test[:,0] == 0))])
np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] < 0) & (treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] < 0) & (treat_test[:,0] == 0))])

-1.0386388239201325

In [133]:
A = np.array([[2],[1],[-1],[-2]])

In [135]:
a

array([[ 2.02733005],
       [ 0.97270765],
       [-1.05386175],
       [-2.06301024]])

In [145]:
A.transpose()

array([[ 2.        ,  1.        , -1.        , -2.        ],
       [ 2.02733005,  0.97270765, -1.05386175, -2.06301024],
       [ 2.02733005,  0.97270765, -1.05386175, -2.06301024],
       [ 2.02733005,  0.97270765, -1.05386175, -2.06301024],
       [ 2.02733005,  0.97270765, -1.05386175, -2.06301024]])

In [125]:
A.transpose()

array([[ 2,  1, -1, -2],
       [ 2,  1, -1, -2]])

In [123]:
A

array([[ 2,  2],
       [ 1,  1],
       [-1, -1],
       [-2, -2]])

In [159]:
mse = []

In [163]:
mse = 

In [165]:
mse

array([1., 1.])

In [11]:
n = 100000
var_e = 0.01
np.random.seed()
#treatment (randomly assigned)
d = np.random.choice([0, 1], size=(n,1), p=[1./2, 1./2])
#covariates (relevate to T.E.)
x1 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
x2 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
x3 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))

#covariates (relevant to outcome)
x4 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
x5 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
#covariates (irrelevant)
x6 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
#error term
e = np.random.normal(loc = 0.0, scale = var_e, size = (n,1))

#indicator functions
ind1 = np.zeros((n,1))
ind2 = np.zeros((n,1))
ind3 = np.zeros((n,1))
ind1[np.where(x1 >= 0)] = 1
ind2[np.where(x2 >= 0)] = 1
ind3[np.where(x3 >= 0)] = 1

y = np.add(np.add(np.add(np.add(d*-5, np.multiply(np.add(np.add(6*ind1, 2.5*ind2),1.5*ind3),d)),x4),x5),e)
X = np.concatenate((x1,x2,x3,x4,x5,x6), axis=1)

x_train, x_test, y_train, y_test, treat_train, treat_test = train_test_split(X, y, d, test_size=0.5)

x1 = x_test[:,0]
x2 = x_test[:,1]
x3 = x_test[:,2]

In [13]:
print(np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] >= 0) & (x_test[:,2] >= 0) &(treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] >= 0) & (x_test[:,2] >= 0) & (treat_test[:,0] == 0))]))
print(np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] >= 0) & (x_test[:,2] >= 0) &(treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] >= 0) & (x_test[:,2] >= 0) & (treat_test[:,0] == 0))]))
print(np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] < 0) & (x_test[:,2] >= 0) &(treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] < 0) & (x_test[:,2] >= 0) & (treat_test[:,0] == 0))]))
print(np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] < 0) & (x_test[:,2] >= 0) &(treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] < 0) & (x_test[:,2] >= 0) & (treat_test[:,0] == 0))]))

print(np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] >= 0) & (x_test[:,2] < 0) &(treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] >= 0) & (x_test[:,2] < 0) & (treat_test[:,0] == 0))]))
print(np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] >= 0) & (x_test[:,2] < 0) &(treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] >= 0) & (x_test[:,2] < 0) & (treat_test[:,0] == 0))]))
print(np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] < 0) & (x_test[:,2] < 0) &(treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] < 0) & (x_test[:,2] < 0) & (treat_test[:,0] == 0))]))
print(np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] < 0) & (x_test[:,2] < 0) &(treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] < 0) & (x_test[:,2] < 0) & (treat_test[:,0] == 0))]))


4.943496378228631
-1.0149439906095452
2.453220359341573
-3.4798282342214333
3.4819902973658063
-2.5079249348333135
0.9835758507480338
-5.000758556533223
