In [39]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

def dgp_ate4_int(n, var_e):
    np.random.seed()
    #treatment (randomly assigned)
    d = np.random.choice([0, 1], size=(n,1), p=[1./2, 1./2])
    #covariates (relevate to T.E.)
    x1 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
    x2 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
    #covariates (relevant to outcome)
    x3 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
    x4 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
    x5 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
    #covariates (irrelevant)
    x6 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
    #error term
    e = np.random.normal(loc = 0.0, scale = var_e, size = (n,1))

    #indicator functions
    ind1 = np.zeros((n,1))
    ind2 = np.zeros((n,1))
    ind3 = np.zeros((n,1))
    ind1[np.where(x1 >= 0)] = 1
    ind2[np.where(x2 >= 0)] = 1
    ind3[np.where((x1 >= 0) & (x2 >= 0))] = 1

    y = np.add(np.add(np.add(np.add(np.add(d*-2, np.multiply(np.add(np.add(3*ind1, ind2), ind3),d)),x3),x4),x5),e)
    X = np.concatenate((x1,x2,x3,x4,x5,x6), axis=1)
    
    x_train, x_test, y_train, y_test, treat_train, treat_test = train_test_split(X, y, d, test_size=0.5)
    
    return x_train, x_test, y_train, y_test, treat_train, treat_test


x_train, x_test, y_train, y_test, treat_train, treat_test = dgp_ate4_int(1000, 0.01)

x1 = x_test[:,0].reshape(-1,1)
x2 = x_test[:,1].reshape(-1,1)
d = treat_test[:,0].reshape(-1,1)
y = y_test[:,0].reshape(-1,1)
print(np.mean(y[np.where((x1 >= 0) & (x2 >= 0) & (d == 1))]) - np.mean(y[np.where((x1 >= 0) & (x2 >= 0) & (d == 0))]))
print(np.mean(y[np.where((x1 >= 0) & (x2 < 0) & (d == 1))]) - np.mean(y[np.where((x1 >= 0) & (x2 < 0) & (d == 0))]))
print(np.mean(y[np.where((x1 < 0) & (x2 >= 0) & (d == 1))]) - np.mean(y[np.where((x1 < 0) & (x2 >= 0) & (d == 0))]))
print(np.mean(y[np.where((x1 < 0) & (x2 < 0) & (d == 1))]) - np.mean(y[np.where((x1 < 0) & (x2 < 0) & (d == 0))]))


3.2717749539416534
1.1372482452795662
-0.7602797972893286
-2.463705184488649


In [19]:
print(np.concatenate((x1,x2,d), axis =1))

[[ 0.22368904 -0.05829291  1.        ]
 [-0.88166315 -0.64107644  0.        ]
 [ 0.99824557 -1.09255274  1.        ]
 ...
 [ 1.41402042 -0.91070444  1.        ]
 [-0.97577507 -0.84529043  1.        ]
 [ 0.05649997  0.46983501  0.        ]]


In [20]:

#print(np.mean(y[np.where((x1 >= 0) & (x2 >= 0) & (d == 1))]) - np.mean(y[np.where((x1 >= 0) & (x2 >= 0) & (d == 0))]))
#print(np.mean(y[np.where((x1 >= 0) & (x2 < 0) & (d == 1))]) - np.mean(y[np.where((x1 >= 0) & (x2 < 0) & (d == 0))]))
#print(np.mean(y[np.where((x1 < 0) & (x2 >= 0) & (d == 1))]) - np.mean(y[np.where((x1 < 0) & (x2 >= 0) & (d == 0))]))
#print(np.mean(y[np.where((x1 < 0) & (x2 < 0) & (d == 1))]) - np.mean(y[np.where((x1 < 0) & (x2 < 0) & (d == 0))]))


array([[ 1],
       [-1],
       [-2],
       [ 2],
       [ 1],
       [ 2],
       [ 1],
       [-2],
       [ 2],
       [-2]])

In [26]:
import timeit


In [25]:


%timeit()


In [23]:
tau

array([-1,  2, -1, -2, -1,  1,  1,  1, -2,  2, -2, -1,  1,  1, -1, -2,  1,
       -1, -1,  2, -2, -1,  1,  2,  1,  1,  1,  1,  1,  2,  2,  1, -2, -1,
        1, -2, -2, -1, -2, -1,  2,  2, -2, -1, -1,  2, -2, -2,  2, -2])

In [45]:
# testing timeit()
import timeit
import_module = '''
import numpy as np
from sklearn.model_selection import train_test_split
'''
testcode = ''' 
def time_test():

'''
print(np.sum(timeit.repeat(stmt=testcode, setup=import_module, repeat = 50)))

7.406819899999391


In [46]:
# testing timeit()
import timeit
import_module = '''
import numpy as np
from sklearn.model_selection import train_test_split
'''
testcode = ''' 
def time_test():
    x_train, x_test, y_train, y_test, treat_train, treat_test = dgp6(1000, 0.01)
    tau = np.where(((x_test[:,0] >= 0) & (x_test[:,1] >= 0)),2, np.where(((x_test[:,0] >= 0) & (x_test[:,1] < 0)),1, np.where(((x_test[:,0] < 0) & (x_test[:,1] >= 0)),-1,-2)))
    return tau
'''
print(np.sum(timeit.repeat(stmt=testcode, setup=import_module, repeat = 50)))

6.8403421999998955


In [75]:
x_train, x_test, y_train, y_test, treat_train, treat_test = dgp6(50000, 0.01)
x1 = x_test[:,0]
x2 = x_test[:,1]
tau1 = np.where(((x1 >= 0) & (x2 >= 0)),2, np.where(((x1 >= 0) & (x2 < 0)),1, np.where(((x1 < 0) & (x2 >= 0)),-1,-2)))

In [76]:
np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] >= 0) & (treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] >= 0) & (treat_test[:,0] == 0))])
np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] < 0) & (treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] >= 0) & (x_test[:,1] < 0) & (treat_test[:,0] == 0))])
np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] >= 0) & (treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] >= 0) & (treat_test[:,0] == 0))])
np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] < 0) & (treat_test[:,0] == 1))]) - np.mean(y_test[np.where((x_test[:,0] < 0) & (x_test[:,1] < 0) & (treat_test[:,0] == 0))])

2.027330047183362

In [133]:
A = np.array([[2],[1],[-1],[-2]])

In [135]:
a

array([[ 2.02733005],
       [ 0.97270765],
       [-1.05386175],
       [-2.06301024]])

In [145]:
A.transpose()

array([[ 2.        ,  1.        , -1.        , -2.        ],
       [ 2.02733005,  0.97270765, -1.05386175, -2.06301024],
       [ 2.02733005,  0.97270765, -1.05386175, -2.06301024],
       [ 2.02733005,  0.97270765, -1.05386175, -2.06301024],
       [ 2.02733005,  0.97270765, -1.05386175, -2.06301024]])

In [125]:
A.transpose()

array([[ 2,  1, -1, -2],
       [ 2,  1, -1, -2]])

In [123]:
A

array([[ 2,  2],
       [ 1,  1],
       [-1, -1],
       [-2, -2]])

In [159]:
mse = []

In [163]:
mse = 

In [165]:
mse

array([1., 1.])