In [3]:
import pandas as pd
from CTL2.causal_tree_learn import CausalTree
from DGP.dgp2 import dgp2
from DGP.dgp1 import dgp1
from DGP.dgp3 import dgp3

from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from CTL.causal_tree_learn import CausalTree as CT2
from random import random

In [46]:
n=10
p=[1./2, 1./2]
d = np.random.choice([0, 1], size=(n,1), p=p)
d_alt = (d-1)*-1


In [47]:
x1 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
x2 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
x3 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
x4 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))    
e = np.random.normal(loc = 0.0, scale = 0.1, size = (n,1))


In [48]:
ind = np.zeros((n,1))
#print(d)
ind[np.where(x1 >= 0)] = 1
#print(ind)
y1 = np.add(d*-1, np.multiply(2, np.multiply(ind,d)))
y1_alt = np.add(d_alt*-1, np.multiply(2, np.multiply(ind,d_alt)))

In [49]:
y2 = np.add(y1, x2)
y3 = np.add(y2, x3)
y4 = np.add(y3, x4)
y = np.add(y4, e)

In [50]:
d, x1

(array([[0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [1],
        [0],
        [1]]),
 array([[-1.13676418],
        [-2.32779969],
        [-0.41699271],
        [-1.38767973],
        [ 1.42727834],
        [-0.20033177],
        [-1.2572951 ],
        [ 1.09776732],
        [-1.00492892],
        [-0.32124246]]))

In [51]:
y = np.add(np.add(np.add(np.add(y1,x2),x3),x4),e)

In [52]:
y_alt = np.add(np.add(np.add(np.add(y1_alt,x2),x3),x4),e)
y_alt

array([[-1.64991241],
       [ 1.55901268],
       [-0.94451772],
       [ 0.80435862],
       [ 0.37323671],
       [ 1.79347817],
       [-1.93489106],
       [-1.00502968],
       [-0.51563644],
       [ 3.753865  ]])

In [62]:
a = np.where(d == 1, y - y_alt, y_alt - y)

In [66]:
b = 

In [69]:
a - b

array([[ 3.33066907e-16],
       [-2.22044605e-16],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 2.22044605e-16],
       [-1.11022302e-16],
       [ 0.00000000e+00],
       [ 0.00000000e+00]])

In [36]:
true[np.where(d == 1) = y - y_alt
true[np.where(d == 0)] = y_alt - y

SyntaxError: invalid syntax (<ipython-input-36-c3a723443efe>, line 1)

In [19]:
n=10
p=[1./2, 1./2]
d = np.random.choice([0, 1], size=(n,1), p=p)
d_alt = (d-1)*-1
x1 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
x2 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
x3 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))
x4 = np.random.normal(loc = 0.0, scale = 1.0, size = (n,1))    
e = np.random.normal(loc = 0.0, scale = 0.1, size = (n,1))
#print(x1)
ind = np.zeros((n,1))
#print(d)
ind[np.where(x1 >= 0)] = 1
#print(ind)
y1 = np.add(d*-1, np.multiply(2, np.multiply(ind,d)))
y1_alt = np.add(d_alt*-1, np.multiply(2, np.multiply(ind,d_alt)))

#print(y1)
y2 = np.add(y1, x2)
y3 = np.add(y2, x3)
y4 = np.add(y3, x4)
y = np.add(y4, e)
y_alt = np.add(np.add(np.add(np.add(y1_alt,x2),x3),x4),e)

In [20]:
d, d_alt

(array([[0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [1]]),
 array([[1],
        [1],
        [0],
        [1],
        [1],
        [1],
        [0],
        [1],
        [0],
        [0]]))

In [4]:
x_train, x_test, y_train, y_test, treat_train, treat_test = dgp3(500)
nomin_test = 0.5
# adaptive CT (Athey and Imbens, PNAS 2016)
ctl = CausalTree(honest=True, weight=0.0, split_size=0.0) #which type of tree to call
ctl.fit(x_train, y_train, treat_train, nomin_test = nomin_test) #select est size when fitting
ctl.prune()
ctl_predict = ctl.predict(x_test)

In [13]:
ctl_predict

array([-1.24800593,  0.86631938,  0.86631938,  1.84454095, -0.74599093,
        0.86631938,  0.55980906,  0.55980906, -1.24800593, -0.74599093,
        1.84454095, -0.74599093, -1.24800593, -0.74599093,  1.84454095,
       -1.24800593,  0.55980906,  0.86631938,  2.25374342, -1.24800593,
        1.84454095,  1.84454095,  1.84454095,  1.84454095,  0.55980906,
        0.86631938,  0.86631938, -1.24800593,  0.86631938,  0.55980906,
        1.84454095, -0.74599093, -0.84303582,  2.25374342,  2.25374342,
        0.86631938, -0.74599093, -0.74599093,  0.86631938,  0.86631938,
        2.25374342,  0.55980906,  0.86631938,  0.55980906, -1.24800593,
       -1.24800593, -1.24800593,  2.25374342,  2.25374342,  0.86631938,
       -0.74599093, -0.84303582, -0.84303582,  0.55980906, -1.24800593,
        1.84454095,  0.55980906,  0.86631938,  0.86631938,  0.55980906,
       -1.24800593, -0.74599093,  0.55980906, -1.24800593,  0.86631938,
        0.55980906,  0.55980906, -1.24800593, -1.24800593,  2.25